apiVersion: v1
kind: Service
metadata:
  labels:
    app: vite
  name: vite
  namespace: vito-app
spec:
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: vite 
  type: NodePort
